### ISSUE TITLE
Consider not using abbreviations

### ISSUE THREAD

**Issue by lpil** [tovedetered/xmleam#1]
Hello!

Very cool project, I was just thinking that I could do with a library like this so I can make an RSS feed :)

The API makes heavy use of abbreviated words such as "opts_cont_tag" which I find hard to understand. For example, I think otps is options, but I don't know what cont is.
In Gleam we really want code to be as easy to understand as possible, so we avoid abbreviations, and I think it might make this library more approachable if it did this too.

Thanks,
Louis

**Comment by tovedetered** [comment]
Hi!

Thanks for your feedback! I have fixed the abbreviations in the old builder module, and (because I was annoyed at Gleam starting to look like JS) I changed things around to be more like gleam/string_builder instead and those functions have much better names in general... I hope. 

Thank you,
Spenser
